### ISSUE TITLE
Incorrect URI for rabbit-hole when TLS is enabled

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/messaging-topology-operator#54]
## Describe the bug
When TLS is enabled and non-TLS listeners are disabled, the user is not created due to an early EOF response.

## To Reproduce
1. Deploy a RabbitMQ cluster with TLS enabled and non-TLS listeners disabled
2. Create a `User` kind
3. Observe the error in the topology operator log

Error in logs:

```
2021-03-12T11:58:23.066Z        ERROR   controller-runtime.manager.controller.user      failed to declare user  {"reconciler group": "rabbitmq.com", "reconciler kind": "User", "name": "foo", "namespace": "default", "user": "foo", "error": "Put \"http://10.96.41.171:15671/api/users/foo\": EOF"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
github.com/rabbitmq/messaging-topology-operator/controllers.(*UserReconciler).declareUser
        /workspace/controllers/user_controller.go:186
github.com/rabbitmq/messaging-topology-operator/controllers.(*UserReconciler).Reconcile
        /workspace/controllers/user_controller.go:94
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:297
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:252
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:215
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:99
```

```yaml
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: bug
spec:
  replicas: 1
  service:
    type: NodePort
  tls:
    secretName: selfsigned-cert-tls
    disableNonTLSListeners: true
```

Certificate and issuer

```yaml
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  dnsNames:
    - bug-632-server-0.bug-632-nodes.svc.cluster.local
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
```

**If we then try to delete de user, we get a panic**

```
2021-03-12T12:09:35.849Z        INFO    controller-runtime.manager.controller.user      Deleting        {"reconciler group": "rabbitmq.com", "reconciler kind": "User", "name": "foo", "namespace": "default"}
E0312 12:09:35.854229       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 338 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x161e880, 0x232a280)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/runtime/runtime.go:48 +0x89
panic(0x161e880, 0x232a280)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/rabbitmq/messaging-topology-operator/controllers.validateResponseForDeletion(0x0, 0x1986de0, 0xc0007cdc50, 0x0, 0x1986de0)
        /workspace/controllers/utils.go:121 +0x29
github.com/rabbitmq/messaging-topology-operator/controllers.(*UserReconciler).deleteUser(0xc00026f240, 0x19bcfc0, 0xc00072c390, 0xc0005e7e00, 0xc000822180, 0x0, 0xc000050aa0)
        /workspace/controllers/user_controller.go:209 +0xbe
github.com/rabbitmq/messaging-topology-operator/controllers.(*UserReconciler).Reconcile(0xc00026f240, 0x19bcfc0, 0xc00072c390, 0xc0007bdca0, 0x7, 0xc0007bdc94, 0x3, 0xc00072c390, 0x40a1df, 0xc000030000, ...)
        /workspace/controllers/user_controller.go:71 +0x6fa
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004575e0, 0x19bcf00, 0xc000109080, 0x1673920, 0xc000501f00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:297 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004575e0, 0x19bcf00, 0xc000109080, 0xc0003ff400)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:252 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x19bcf00, 0xc000109080)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:215 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000539f50)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000b2bf50, 0x1986580, 0xc000796c90, 0xc000109001, 0xc000018000)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000539f50, 0x3b9aca00, 0x0, 0x1, 0xc000018000)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x19bcf00, 0xc000109080, 0xc000789860, 0x3b9aca00, 0x0, 0x1)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x19bcf00, 0xc000109080, 0xc000789860, 0x3b9aca00)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:212 +0x45e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14e7a29]
```

**Expected behavior**
The User is created in RabbitMQ and topology operator does not log any error.

## Version and environment information
- Messaging Topology Operator: 0.3.0
- RabbitMQ: 3.8.12
- RabbitMQ Cluster Operator: 1.5.0
- Kubernetes: 1.20.2
- Cloud provider or hardware configuration: KinD
 
## Additional context
The problem seems to be in the URI construction, we use protocol `http` regardless of whether we are targeting a TLS listener.

**Comment by michaelklishin** [comment]
Sounds like something `rabbit-hole` could take care of as well. I'd consider a PR :)
