### ISSUE TITLE
Panic in reconcile loop

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/messaging-topology-operator#88]
## Describe the bug
The messaging topology operator Pod is in crash loop backoff. 

## To Reproduce
I haven't reproduced the problem in KinD. The setup I have is:

- Two RabbitMQ clusters in two different namespaces
- Schema sync plugin enabled. One cluster synchronises from the other
- User `schema-sync` CR created in both namespaces
- User object `schema-sync` has a deletion timestamp in its metadata
- Topology Operator is getting a 401 error when it contacts RabbitMQ API

**Expected behavior**
The topology operator handles the response from the API and doesn't crash.

## Screenshots

Log fragment of the panic

```
2021-03-29T11:07:13.337Z        INFO    controller-runtime.manager.controller.user      Deleting        {"reconciler group": "rabbitmq.com", "reconciler kind": "User", "name": "schema-sync", "namespace": "aitor-secondary"}
2021-03-29T11:07:13.337Z        INFO    controller-runtime.manager.controller.user      Successfully retrieved credentials      {"reconciler group": "rabbitmq.com", "reconciler kind": "User", "name": "schema-sync", "namespace": "aitor-secondary", "user": "schema-sync", "secretCredentials": "&LocalObjectReference{Name:schema-sync-user-credentials,}"}
2021-03-29T11:07:13.337Z        INFO    controller-runtime.manager.controller.queue     Start reconciling       {"reconciler group": "rabbitmq.com", "reconciler kind": "Queue", "name": "invoices", "namespace": "aitor-primary", "spec": "{\"name\":\"invoices\",\"vhost\":\"/\",\"type\":\"quorum\",\"durable\":true,\"rabbitmqClusterReference\":{\"name\":\"aitor-primary\"}}"}
2021-03-29T11:07:13.337Z        INFO    controller-runtime.manager.controller.exchange  Start reconciling       {"reconciler group": "rabbitmq.com", "reconciler kind": "Exchange", "name": "x-test", "namespace": "aitor-primary", "spec": "{\"name\":\"x-test\",\"vhost\":\"/\",\"type\":\"direct\",\"durable\":true,\"rabbitmqClusterReference\":{\"name\":\"aitor-primary\"}}"}
E0329 11:07:13.341975       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 425 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x157ae40, 0x22b2540)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/runtime/runtime.go:48 +0x86
panic(0x157ae40, 0x22b2540)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rabbitmq/messaging-topology-operator/controllers.validateResponseForDeletion(0x0, 0x1942de0, 0xc0006e2d40, 0x0, 0x1942de0)
        /workspace/controllers/utils.go:131 +0x29
github.com/rabbitmq/messaging-topology-operator/controllers.(*UserReconciler).deleteUser(0xc0002ab5c0, 0x1973118, 0xc000795830, 0xc000079140, 0xc00045d980, 0x0, 0xc000387a00)
        /workspace/controllers/user_controller.go:320 +0x327
github.com/rabbitmq/messaging-topology-operator/controllers.(*UserReconciler).Reconcile(0xc0002ab5c0, 0x1973118, 0xc000795830, 0xc000387a00, 0xf, 0xc0003879e0, 0xb, 0xc000795830, 0xc000030000, 0x15f8080, ...)
        /workspace/controllers/user_controller.go:77 +0xed5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000422140, 0x1973070, 0xc00037e340, 0x15c4b00, 0xc0007393c0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000422140, 0x1973070, 0xc00037e340, 0x200c000132c00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x1973070, 0xc00037e340)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000028f50)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0005e5f50, 0x19446e0, 0xc0007957a0, 0xc00037e301, 0xc0005b2ae0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000028f50, 0x3b9aca00, 0x0, 0xc000172f01, 0xc0005b2ae0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1973070, 0xc00037e340, 0xc0006e28c0, 0x3b9aca00, 0x0, 0xc000313801)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1973070, 0xc00037e340, 0xc0006e28c0, 0x3b9aca00)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:213 +0x40d
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1469389]

goroutine 425 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/runtime/runtime.go:55 +0x109
panic(0x157ae40, 0x22b2540)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rabbitmq/messaging-topology-operator/controllers.validateResponseForDeletion(0x0, 0x1942de0, 0xc0006e2d40, 0x0, 0x1942de0)
        /workspace/controllers/utils.go:131 +0x29
github.com/rabbitmq/messaging-topology-operator/controllers.(*UserReconciler).deleteUser(0xc0002ab5c0, 0x1973118, 0xc000795830, 0xc000079140, 0xc00045d980, 0x0, 0xc000387a00)
        /workspace/controllers/user_controller.go:320 +0x327
github.com/rabbitmq/messaging-topology-operator/controllers.(*UserReconciler).Reconcile(0xc0002ab5c0, 0x1973118, 0xc000795830, 0xc000387a00, 0xf, 0xc0003879e0, 0xb, 0xc000795830, 0xc000030000, 0x15f8080, ...)
        /workspace/controllers/user_controller.go:77 +0xed5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000422140, 0x1973070, 0xc00037e340, 0x15c4b00, 0xc0007393c0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000422140, 0x1973070, 0xc00037e340, 0x200c000132c00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x1973070, 0xc00037e340)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000028f50)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0005e5f50, 0x19446e0, 0xc0007957a0, 0xc00037e301, 0xc0005b2ae0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000028f50, 0x3b9aca00, 0x0, 0xc000172f01, 0xc0005b2ae0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1973070, 0xc00037e340, 0xc0006e28c0, 0x3b9aca00, 0x0, 0xc000313801)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1973070, 0xc00037e340, 0xc0006e28c0, 0x3b9aca00)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:213 +0x40d
```

## Version and environment information
- Messaging Topology Operator: 0.4.1
- RabbitMQ: 3.8.12
- RabbitMQ Cluster Operator: 1.5.0
- Kubernetes: 1.18
- Cloud provider or hardware configuration: GKE

**Comment by Zerpet** [comment]
This seems to have some potential to cause a "chicken-and-egg" problem. If I try to delete the top-op related resources, it waits for the finalizer to be removed:

```
4:12:49PM: ---- waiting on 5 changes [53/58 done] ----
4:13:01PM: ongoing: delete namespace/rabbitmq-red (v1) cluster
4:13:01PM: ongoing: delete queue/test (rabbitmq.com/v1alpha2) namespace: rabbitmq-red
4:13:01PM: ongoing: delete user/replicator (rabbitmq.com/v1alpha2) namespace: rabbitmq-red
4:13:02PM: ongoing: delete queue/invoices (rabbitmq.com/v1alpha2) namespace: rabbitmq-red
4:13:04PM: ongoing: delete binding/x-invoices-to-invoices (rabbitmq.com/v1alpha2) namespace: rabbitmq-red
```

However the top-op Pod is in crash loop backoff, so it will never remove the finalizer. If I try to `k edit` the resource to manually remove the finalizer, I get an error related to no end-point available for the webhook (because the top-op Pod is in crash loop backoff):


```bash
k edit bindings.rabbitmq.com x-invoices-to-invoices
# error: bindings.rabbitmq.com "x-invoices-to-invoices" could not be patched: Internal error occurred: failed calling webhook "vbinding.kb.io": Post https://webhook-service.rabbitmq-system.svc:443/validate-rabbitmq-com-v1alpha2-binding?timeout=10s: no endpoints available for service "webhook-service"
# You can run `kubectl replace -f /var/folders/6w/djnkjr615bl67tgv135mp0d40000gp/T/kubectl-edit-bjd65.yaml` to try this update again.

kubectl replace -f /var/folders/6w/djnkjr615bl67tgv135mp0d40000gp/T/kubectl-edit-bjd65.yaml
# Error from server (InternalError): error when replacing "/var/folders/6w/djnkjr615bl67tgv135mp0d40000gp/T/kubectl-edit-bjd65.yaml": Internal error occurred: failed calling webhook "vbinding.kb.io": Post https://webhook-service.rabbitmq-system.svc:443/validate-rabbitmq-com-v1alpha2-binding?timeout=10s: no endpoints available for service "webhook-service"
```

**Comment by Zerpet** [comment]
Run into another panic in the top-op. The stack trace is different, but I was wondering if the fix @coro is working on would fix this as well?
Or should I open a new bug report?

The stack trace:

```
2021-04-06T09:07:59.848Z        INFO    controller-runtime.manager.controller.binding   Deleting        {"reconciler group": "rabbitmq.com", "reconciler kind": "Binding", "name": "x-invoices-to-invoices", "namespace": "rabbitmq-red"}
E0406 09:07:59.849198       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 374 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1581480, 0x22be540)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1581480, 0x22be540)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/michaelklishin/rabbit-hole/v2.newRequestWithBody(0x0, 0x171d9c8, 0x6, 0xc00099e990, 0x26, 0x0, 0x0, 0x0, 0x7f9f229665a0, 0xc0005e9728, ...)
        /go/pkg/mod/github.com/michaelklishin/rabbit-hole/v2@v2.6.0/client.go:100 +0x37
github.com/michaelklishin/rabbit-hole/v2.(*Client).DeleteBinding(0x0, 0x22808b8, 0x1, 0xc000047d30, 0xa, 0x22808b8, 0x1, 0xc000047d20, 0x8, 0xc000047d28, ...)
        /go/pkg/mod/github.com/michaelklishin/rabbit-hole/v2@v2.6.0/bindings.go:217 +0x330
github.com/rabbitmq/messaging-topology-operator/controllers.(*BindingReconciler).deleteBinding(0xc000422900, 0x197ab58, 0xc00077d590, 0x0, 0xc000754d00, 0x0, 0xc000047cd0)
        /workspace/controllers/binding_controller.go:156 +0x17b
github.com/rabbitmq/messaging-topology-operator/controllers.(*BindingReconciler).Reconcile(0xc000422900, 0x197ab58, 0xc00077d590, 0xc000047cd0, 0xc, 0xc000403170, 0x16, 0xc00077d590, 0xc000030000, 0x15feb80, ...)
        /workspace/controllers/binding_controller.go:67 +0xcfe
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002e8140, 0x197aab0, 0xc000326000, 0x15cb320, 0xc000774a80)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298 +0x30d
[...controller-runtime-stuff...]
```
